name: Generate APK Debug

on:
  # Triggers the workflow on push or pull request events but only for default and protected branches
  push:
    branches:
      - master
      - debug
  pull_request:
    branches: 
      - master
      - debug
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test

      # Create APK Debug
      - name: Build apk debug
        run: ./gradlew assembleDebug

      # Upload Artifact Build
      # Noted For Output [module-name]/build/outputs/apk
      - name: Upload apk debug
        uses: actions/upload-artifact@v2
        with:
          name: FoxMmm-debug.apk
          path: app/build/outputs/apk/default/debug/app-default-debug.apk

      - name: Upload apk debug-fdroid
        uses: actions/upload-artifact@v2
        with:
          name: FoxMmm-fdroid-debug.apk
          path: app/build/outputs/apk/fdroid/debug/app-fdroid-debug.apk
